#!/usr/bin/env python3
"""
Converts the EDCAS logo PNG to ratatui Rust code using the ▀ half-block technique.
Each terminal cell = 2 vertical pixels: fg = top pixel, bg = bottom pixel.
Transparent pixels fall back to Color::Reset (terminal background).
"""
from PIL import Image
import sys

TARGET_WIDTH = 90          # characters wide in the terminal
ALPHA_THRESHOLD = 30       # pixels below this alpha are treated as transparent
OUT_FILE = "src/views/logo_lines.rs"

img = Image.open("assets/graphics/logo/edcas.png").convert("RGBA")

# Terminal cells are ~2× taller than wide, so halve the pixel-height to
# keep the correct aspect ratio.
scale = TARGET_WIDTH / img.width
px_width  = TARGET_WIDTH
px_height = max(2, int(img.height * scale * 0.5) * 2)  # must be even

img = img.resize((px_width, px_height), Image.LANCZOS)
pixels = img.load()

lines = []
for y in range(0, px_height, 2):
    spans = []
    for x in range(px_width):
        rt, gt, bt, at = pixels[x, y]
        rb, gb, bb, ab = pixels[x, y + 1]

        top_opaque    = at >= ALPHA_THRESHOLD
        bottom_opaque = ab >= ALPHA_THRESHOLD

        if not top_opaque and not bottom_opaque:
            spans.append('        Span::raw(" "),')
        elif top_opaque and not bottom_opaque:
            spans.append(
                f'        Span::styled("▀", Style::default()'
                f'.fg(Color::Rgb({rt},{gt},{bt}))'
                f'.bg(Color::Reset)),'
            )
        elif not top_opaque and bottom_opaque:
            spans.append(
                f'        Span::styled("▄", Style::default()'
                f'.fg(Color::Rgb({rb},{gb},{bb}))'
                f'.bg(Color::Reset)),'
            )
        else:
            spans.append(
                f'        Span::styled("▀", Style::default()'
                f'.fg(Color::Rgb({rt},{gt},{bt}))'
                f'.bg(Color::Rgb({rb},{gb},{bb}))),'
            )
    lines.append(spans)

# Build Rust function
out = []
out.append("// Generated by assets/logo_to_rust.py — do not edit manually.")
out.append("fn logo_lines() -> Vec<Line<'static>> {")
out.append("    vec![")
for spans in lines:
    out.append("        Line::from(vec![")
    for s in spans:
        out.append("    " + s)
    out.append("        ]),")
out.append("    ]")
out.append("}")

result = "\n".join(out)
with open(OUT_FILE, "w") as f:
    f.write(result)

print(f"Written {len(lines)} lines × {TARGET_WIDTH} chars → {OUT_FILE}")
